import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#274449",
        "inverse-surface": "#fdf8ff",
        "tertiary-container": "#ead1fb",
        "on-tertiary-fixed": "#443354",
        "on-tertiary-fixed-variant": "#624f72",
        "on-secondary-container": "#b7d6dc",
        "surface-container-high": "#211d32",
        "secondary-dim": "#bbdae0",
        "primary-fixed": "#c7b9f5",
        "on-background": "#ece5fc",
        "primary-container": "#a698d2",
        "on-error-container": "#ffb2b9",
        /* ── Themeable via CSS variables ── */
        primary:              "rgb(var(--color-primary) / <alpha-value>)",
        secondary:            "rgb(var(--color-secondary) / <alpha-value>)",
        tertiary:             "rgb(var(--color-tertiary) / <alpha-value>)",
        background:           "rgb(var(--color-background) / <alpha-value>)",
        surface:              "rgb(var(--color-surface) / <alpha-value>)",
        "on-surface":         "rgb(var(--color-on-surface) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--color-on-surface-variant) / <alpha-value>)",
        "on-primary":         "rgb(var(--color-on-primary) / <alpha-value>)",
        /* ── Static dark-mode tokens (unchanged) ── */
        "inverse-primary": "#63578c",
        "surface-container-low": "#141123",
        "inverse-on-surface": "#575266",
        outline: "#787387",
        "error-dim": "#d73357",
        "surface-dim": "#0f0c1c",
        "primary-dim": "#b9abe6",
        "surface-tint": "#c7b9f5",
        "on-secondary-fixed-variant": "#436065",
        "surface-container-lowest": "#000000",
        "surface-variant": "#27233a",
        "on-primary-fixed-variant": "#493e71",
        "error-container": "#a70138",
        "surface-bright": "#2d2942",
        "on-error": "#490013",
        "on-secondary": "#39565c",
        "on-primary-fixed": "#2b1f51",
        "secondary-container": "#2e4b50",
        "surface-container-highest": "#27233a",
        "tertiary-dim": "#dbc3ed",
        error: "#ff6e84",
        "outline-variant": "#494558",
        "primary-fixed-dim": "#b9abe6",
        "tertiary-fixed-dim": "#dbc3ed",
        "secondary-fixed-dim": "#bbdae0",
        "on-primary-container": "#261a4b",
        "tertiary-fixed": "#ead1fb",
        "on-tertiary-container": "#584568",
        "surface-container": "#1a172a",
        "on-tertiary": "#604e70",
        "secondary-fixed": "#c9e8ee",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        "3xl": "2.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        label: ["var(--font-inter)", "Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
